### ISSUE TITLE
C&C server closing immediatley

### ISSUE THREAD

**Issue by nellaisamurai** [SPB-Production/Spacenet#1]
http://prntscr.com/izxomd

c&c server closing immediately..what might be the issue!!

**Comment by SPB-Production** [comment]
I don't think it is an issue because it has been tested on virgin systems ... but by what I see from your screenshot your launched apache2 . Spacenet has an its own integrated cherrypy webserver so apache2 is not necessary , in my opinion try to close apache2 it might be conflict with 80 or 8080 port which Spacenet is trying to run . And be sure no process is already running on those ports .
